import React from "react";

export const lightStyles: { [key: string]: React.CSSProperties } = {
  loadingContainer: {
    minHeight: '100dvh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #F5F4F0 0%, #EDECE8 100%)',
  },
  loadingContent: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '16px',
  },
  loadingLogo: {
    width: '72px',
    height: '72px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingLogoImg: {
    width: '100%',
    height: '100%',
    objectFit: 'contain' as const,
  },
  loadingBrand: {
    fontSize: '20px',
    fontWeight: 600,
    color: '#1A1918',
    letterSpacing: '-0.02em',
  },
  loadingDots: {
    display: 'flex',
    gap: '8px',
    marginTop: '8px',
  },
  loadingDot: {
    background: '#D08A30',
  },
  limitWarning: {
    padding: '12px 16px',
    background: 'rgba(208, 138, 48, 0.1)',
    border: '1px solid rgba(208, 138, 48, 0.3)',
    borderRadius: '8px',
    marginBottom: '12px',
    fontSize: '14px',
    color: '#D08A30',
  },
  upgradeLink: {
    color: '#D08A30',
    cursor: 'pointer',
    fontWeight: 600,
    textDecoration: 'underline',
  },
  messageLimitInfo: {
    fontSize: '14px',
    color: '#9A9590',
    marginTop: '16px',
  },
  promptGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    marginTop: '20px',
    maxWidth: '500px',
    width: '100%',
  },
  promptGridMobile: {
    gridTemplateColumns: '1fr',
  },
  promptChip: {
    padding: '10px 16px',
    borderRadius: '999px',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    background: '#EDECE8',
    color: '#6B6660',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    textAlign: 'center' as const,
    transition: 'background 0.15s, border-color 0.15s',
    lineHeight: 1.4,
  },
  promptChipHover: {
    padding: '10px 16px',
    borderRadius: '999px',
    border: '1px solid #D08A30',
    background: 'rgba(208, 138, 48, 0.1)',
    color: '#D08A30',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    textAlign: 'center' as const,
    transition: 'background 0.15s, border-color 0.15s',
    lineHeight: 1.4,
  },
  quickChip: {
    padding: '10px 18px',
    borderRadius: '100px',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    background: '#EDECE8',
    color: '#6B6660',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
  },
  quickChipHover: {
    padding: '10px 18px',
    borderRadius: '100px',
    border: '1px solid #D08A30',
    background: 'rgba(208, 138, 48, 0.1)',
    color: '#D08A30',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
    transform: 'translateY(-2px)',
    boxShadow: '0 4px 16px rgba(208, 138, 48, 0.1)',
  },
  chipIcon: {
    width: '20px',
    height: '20px',
    borderRadius: '6px',
    background: '#E4E3DF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    flexShrink: 0,
  },
  remainingMessages: {
    color: '#9A9590',
    fontSize: '11px',
  },
  authContainer: {
    height: '100dvh',
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    background: '#F5F4F0',
    position: 'fixed' as const,
    top: 0,
    left: 0,
    overflow: 'hidden' as const,
    touchAction: 'none' as const,
    overscrollBehavior: 'none' as const,
  },
  authThemeToggle: {
    position: 'absolute' as const,
    top: '24px',
    right: '24px',
    background: '#EDECE8',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '10px',
    padding: '10px 14px',
    fontSize: '18px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    zIndex: 10,
  },
  authCard: {
    width: '100%',
    maxWidth: '400px',
    padding: '36px 32px',
    margin: 'auto',
    background: 'rgba(255, 255, 255, 0.65)',
    borderRadius: '24px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.08)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: '1px solid rgba(255, 255, 255, 0.4)',
    position: 'relative' as const,
    zIndex: 1,
  },
  authLogo: {
    textAlign: 'center' as const,
    marginBottom: '20px',
  },
  logoIcon: {
    width: '56px',
    height: '56px',
    margin: '0 auto 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoIconImg: {
    width: '100%',
    height: '100%',
    objectFit: 'contain' as const,
  },
  authTitle: {
    fontSize: '26px',
    fontWeight: 600,
    marginBottom: '6px',
    color: '#1A1918',
    letterSpacing: '-0.02em',
  },
  authSubtitle: {
    fontSize: '14px',
    color: '#9A9590',
  },
  authError: {
    padding: '12px 16px',
    background: 'rgba(232, 90, 90, 0.1)',
    borderLeft: '4px solid #E85A5A',
    borderRadius: '8px',
    color: '#E85A5A',
    fontSize: '14px',
    marginBottom: '20px',
  },
  authSuccess: {
    padding: '12px 16px',
    background: 'rgba(16, 185, 129, 0.1)',
    borderLeft: '4px solid #10b981',
    borderRadius: '8px',
    color: '#10b981',
    fontSize: '14px',
    marginBottom: '20px',
  },
  tabContainer: {
    display: 'flex',
    gap: '8px',
    marginBottom: '24px',
    background: '#E4E3DF',
    padding: '4px',
    borderRadius: '12px',
  },
  tab: {
    flex: 1,
    padding: '10px 16px',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    background: 'transparent',
    color: '#9A9590',
    transition: 'all 0.3s ease',
  },
  tabActive: {
    background: 'rgba(208, 138, 48, 0.1)',
    color: '#D08A30',
    boxShadow: 'none',
  },
  formGroup: {
    marginBottom: '16px',
  },
  labelRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    fontSize: '13px',
    fontWeight: 500,
    color: '#6B6660',
  },
  forgotLink: {
    fontSize: '12px',
    color: '#6B6660',
    cursor: 'pointer',
    fontWeight: 400,
    transition: 'color 0.3s ease',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '10px',
    fontSize: '16px',
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, sans-serif',
    background: '#EDECE8',
    color: '#1A1918',
    boxSizing: 'border-box' as const,
    transition: 'all 0.3s ease',
    outline: 'none',
  },
  authBtn: {
    width: '100%',
    padding: '13px 24px',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    background: 'linear-gradient(135deg, #D08A30, #C05A30)',
    color: '#fff',
    transition: 'all 0.3s ease',
    marginTop: '20px',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    margin: '20px 0',
    color: '#9A9590',
    fontSize: '12px',
  },
  dividerLine: {
    flex: 1,
    height: '1px',
    background: 'rgba(0, 0, 0, 0.07)',
  },
  dividerText: {
    padding: '0 16px',
    fontSize: '12px',
    color: '#9A9590',
    fontWeight: 400,
  },
  socialButtons: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
  },
  authSwitch: {
    textAlign: 'center' as const,
    marginTop: '24px',
    fontSize: '14px',
    color: '#6B6660',
  },
  authLink: {
    color: '#D08A30',
    cursor: 'pointer',
    fontWeight: 600,
  },
  checkEmailContainer: {
    textAlign: 'center' as const,
    padding: '20px 0',
  },
  emailIconWrapper: {
    position: 'relative' as const,
    width: '80px',
    height: '80px',
    margin: '0 auto 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailIcon: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    background: 'rgba(208, 138, 48, 0.1)',
    border: '2px solid rgba(208, 138, 48, 0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#D08A30',
    zIndex: 2,
    position: 'relative' as const,
  },
  emailIconRing: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    border: '2px solid rgba(208, 138, 48, 0.2)',
    zIndex: 1,
  },
  checkEmailTitle: {
    fontSize: '24px',
    fontWeight: 600,
    color: '#1A1918',
    marginBottom: '12px',
  },
  checkEmailText: {
    fontSize: '14px',
    color: '#6B6660',
    marginBottom: '4px',
  },
  checkEmailAddress: {
    fontSize: '15px',
    fontWeight: 600,
    color: '#D08A30',
    marginBottom: '16px',
  },
  checkEmailSubtext: {
    fontSize: '13px',
    color: '#9A9590',
    marginBottom: '24px',
    lineHeight: 1.5,
  },
  app: {
    display: 'flex',
    height: '100dvh',
    width: '100vw',
    maxWidth: '100%',
    overflow: 'hidden',
    position: 'relative' as const,
  },
  mobileOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    zIndex: 999,
    backdropFilter: 'blur(4px)',
    WebkitBackdropFilter: 'blur(4px)',
  },
  mobileMenuBtn: {
    background: 'none',
    border: 'none',
    fontSize: '20px',
    cursor: 'pointer',
    padding: '4px 8px',
    color: '#1A1918',
    marginRight: '12px',
  },
  mobileMenuDots: {
    position: 'absolute' as const,
    right: '4px',
    top: '50%',
    transform: 'translateY(-50%)',
    fontSize: '18px',
    padding: '10px 12px',
    minWidth: '44px',
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#666',
  },
  sidebar: {
    width: '280px',
    background: '#EDECE8',
    borderRight: '1px solid rgba(0, 0, 0, 0.07)',
    display: 'flex',
    flexDirection: 'column' as const,
    transition: 'width 0.3s ease, opacity 0.3s ease',
    overflow: 'hidden',
    flexShrink: 0,
    position: 'relative' as const,
    height: '100dvh',
  },
  sidebarCollapsed: {
    width: '0px',
    opacity: 0,
    overflow: 'hidden',
    pointerEvents: 'none' as const,
    padding: 0,
    borderRight: 'none',
  },
  sidebarTop: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  sidebarHeader: {
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.07)',
  },
  sidebarToggle: {
    background: 'none',
    border: 'none',
    fontSize: '18px',
    cursor: 'pointer',
    padding: '6px',
    color: '#6B6660',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background 0.15s ease',
    flexShrink: 0,
  },
  brandContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'opacity 0.2s ease, width 0.2s ease',
    overflow: 'hidden',
    whiteSpace: 'nowrap' as const,
  },
  brandLogo: {
    width: '24px',
    height: '24px',
    objectFit: 'contain' as const,
  },
  brand: {
    fontWeight: 600,
    fontSize: '15px',
    letterSpacing: '-0.03em',
    color: '#1A1918',
    whiteSpace: 'nowrap' as const,
    display: 'flex',
    alignItems: 'center',
    transition: 'opacity 0.2s ease, width 0.2s ease',
  },
  section: {
    padding: '12px 16px 8px',
    borderBottom: 'none',
  },
  newChatBtn: {
    width: '100%',
    padding: '10px 16px',
    borderRadius: '10px',
    border: '1px dashed rgba(0, 0, 0, 0.13)',
    background: 'transparent',
    color: '#6B6660',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.25s ease',
  },
  newChatBtnHover: {
    width: '100%',
    padding: '10px 16px',
    borderRadius: '10px',
    border: '1px dashed #D08A30',
    background: 'rgba(208, 138, 48, 0.1)',
    color: '#D08A30',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: 'all 0.25s ease',
  },
  collapseBtn: {
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    background: 'transparent',
    color: '#9A9590',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    flexShrink: 0,
    transition: 'all 0.2s ease',
  },
  expandBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    background: 'transparent',
    color: '#6B6660',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
    flexShrink: 0,
    marginRight: '12px',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 12px',
    borderRadius: '12px',
    cursor: 'pointer',
    marginBottom: '4px',
    transition: 'all 0.2s ease',
  },
  navIcon: {
    fontSize: '18px',
    width: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navText: {
    fontSize: '15px',
    color: '#1A1918',
    transition: 'opacity 0.2s ease, width 0.2s ease',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden' as const,
  },
  sectionLabel: {
    padding: '12px 16px 8px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#9A9590',
    transition: 'opacity 0.2s ease',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.3px',
  },
  recentsList: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '0 10px',
  },
  chatItemWrapper: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
    marginBottom: '2px',
  },
  recentItem: {
    flex: 1,
    padding: '10px 12px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 500,
    color: '#1A1918',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    position: 'relative' as const,
    transition: 'background 0.15s ease',
  },
  recentItemActive: {
    background: 'rgba(208, 138, 48, 0.08)',
    boxShadow: 'inset 3px 0 0 #D08A30',
    borderRadius: '0 10px 10px 0',
    fontWeight: 500,
    color: '#1A1918',
  },
  chatActions: {
    display: 'flex',
    gap: '4px',
    marginLeft: '4px',
  },
  actionBtn: {
    background: 'none',
    border: 'none',
    fontSize: '14px',
    cursor: 'pointer',
    padding: '4px 6px',
    borderRadius: '4px',
    opacity: 0.7,
  },
  renameWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    width: '100%',
    padding: '4px 8px',
    boxSizing: 'border-box' as const,
  },
  renameInput: {
    flex: 1,
    minWidth: 0,
    padding: '6px 10px',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '6px',
    fontSize: '16px', // 16px prevents iOS auto-zoom
    outline: 'none',
    fontFamily: 'inherit',
    background: '#F5F4F0',
  },
  renameIconBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    background: '#10b981',
    border: 'none',
    color: 'white',
    borderRadius: '6px',
    cursor: 'pointer',
    flexShrink: 0,
  },
  cancelIconBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    background: '#ef4444',
    border: 'none',
    color: 'white',
    borderRadius: '6px',
    cursor: 'pointer',
    flexShrink: 0,
  },
  renameBtn: {
    background: '#10b981',
    border: 'none',
    color: 'white',
    padding: '6px 10px',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  cancelBtn: {
    background: '#ef4444',
    border: 'none',
    color: 'white',
    padding: '6px 10px',
    borderRadius: '4px',
    fontSize: '14px',
    cursor: 'pointer',
  },
  sidebarFooter: {
    padding: '16px',
    borderTop: '1px solid rgba(0, 0, 0, 0.07)',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  avatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #D08A30, #C05A30)',
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
    fontSize: '14px',
    flexShrink: 0,
  },
  userInfo: {
    flex: 1,
    overflow: 'hidden',
    transition: 'opacity 0.2s ease, width 0.2s ease',
    whiteSpace: 'nowrap' as const,
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    background: '#F5F4F0',
    overflow: 'hidden',
    maxWidth: '100%',
    position: 'relative' as const,
    backgroundImage: 'radial-gradient(ellipse 80% 50% at 50% 0%, rgba(208, 138, 48, 0.05), transparent), radial-gradient(circle at 80% 90%, rgba(192, 90, 48, 0.02), transparent)',
  },
  topBar: {
    padding: '12px 16px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.07)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    maxWidth: '100%',
  },
  topBarLeft: {
    display: 'flex',
    alignItems: 'center',
    overflow: 'hidden',
  },
  modelBadge: {
    fontSize: '15px',
    fontWeight: 500,
    color: '#6B6660',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '400px',
    flex: 1,
  },
  topBarRight: {
    display: 'flex',
    alignItems: 'center',
  },
  iconBtn: {
    background: 'none',
    border: 'none',
    fontSize: '20px',
    cursor: 'pointer',
    padding: '8px',
    borderRadius: '10px',
    transition: 'background 0.15s ease',
  },
  chatWrapper: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    maxWidth: '100%',
    position: 'relative' as const,
  },
  messagesArea: {
    flex: 1,
    overflowY: 'auto' as const,
    overflowX: 'hidden' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    maxWidth: '100%',
  },
  scrollToBottomBtn: {
    position: 'absolute' as const,
    bottom: '160px',
    left: '50%',
    transform: 'translateX(-50%)',
    zIndex: 200,
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    background: 'rgba(237, 236, 232, 0.95)',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#6B6660',
    transition: 'all 0.2s ease',
  },
  emptyState: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
  },
  greetingLogo: {
    width: '72px',
    height: '72px',
    marginBottom: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  greetingLogoImg: {
    width: '100%',
    height: '100%',
    objectFit: 'contain' as const,
  },
  greetingText: {
    fontSize: '28px',
    fontWeight: 700,
    color: '#1A1918',
    marginBottom: '24px',
    textAlign: 'center' as const,
    maxWidth: '500px',
    lineHeight: 1.4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatMessages: {
    maxWidth: '768px',
    width: '100%',
    margin: '0 auto',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
    boxSizing: 'border-box' as const,
  },
  chatMessagesMobile: {
    padding: '12px 8px',
    maxWidth: '100%',
    boxSizing: 'border-box' as const,
  },
  messageRowUser: {
    display: 'flex',
    width: '100%',
    justifyContent: 'flex-end',
    maxWidth: '100%',
    paddingTop: '1px',
    paddingBottom: '1px',
  },
  messageRowAssistant: {
    display: 'flex',
    width: '100%',
    justifyContent: 'flex-start',
    maxWidth: '100%',
    paddingTop: '1px',
    paddingBottom: '1px',
  },
  messageBubbleUser: {
    padding: '12px 16px',
    borderRadius: '14px 14px 4px 14px',
    fontSize: '15px',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    overflowWrap: 'break-word' as const,
    background: 'rgba(208, 138, 48, 0.12)',
    color: '#1A1918',
    boxSizing: 'border-box' as const,
    boxShadow: 'none',
  },
  messageBubbleAssistant: {
    maxWidth: '90%',
    padding: '12px 16px',
    borderRadius: '14px 14px 14px 4px',
    fontSize: '15px',
    lineHeight: 1.5,
    wordWrap: 'break-word' as const,
    wordBreak: 'break-word' as const,
    overflowWrap: 'break-word' as const,
    background: '#EDECE8',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    color: '#1A1918',
    boxSizing: 'border-box' as const,
    boxShadow: 'none',
  },
  messageText: {
    wordBreak: 'normal' as const,
    overflowWrap: 'break-word' as const,
  },
  messageWrapper: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    gap: '4px',
    width: 'fit-content' as const,
    maxWidth: '90%',
  },
  messageWrapperUser: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-end',
    gap: '4px',
    width: 'fit-content' as const,
    maxWidth: '90%',
    marginLeft: 'auto',
  },
  messageActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
    opacity: 0.5,
    marginTop: '4px',
    marginLeft: '4px',
  },
  messageActionsUser: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
    opacity: 0.5,
    marginTop: '4px',
    marginRight: '4px',
  },
  editModeContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
    width: '100%',
    maxWidth: '600px',
  },
  editTextarea: {
    width: '100%',
    minHeight: '100px',
    padding: '14px 16px',
    fontSize: '16px',
    fontFamily: 'inherit',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '12px',
    resize: 'vertical' as const,
    outline: 'none',
    background: '#EDECE8',
    color: '#1A1918',
    lineHeight: 1.5,
  },
  editWarning: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '8px',
    fontSize: '13px',
    color: '#8e8e93',
    lineHeight: 1.4,
  },
  editActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  editCancelBtn: {
    padding: '10px 20px',
    fontSize: '15px',
    fontWeight: 500,
    border: 'none',
    borderRadius: '10px',
    background: '#E4E3DF',
    color: '#1A1918',
    cursor: 'pointer',
    transition: 'background 0.15s ease',
  },
  editSaveBtn: {
    padding: '10px 20px',
    fontSize: '15px',
    fontWeight: 600,
    border: 'none',
    borderRadius: '10px',
    background: 'linear-gradient(135deg, #D08A30, #C05A30)',
    color: '#fff',
    cursor: 'pointer',
    transition: 'background 0.15s ease',
  },
  messageTimestamp: {
    fontSize: '11px',
    color: '#9A9590',
  },
  actionButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '6px',
    borderRadius: '8px',
    color: '#9A9590',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'color 0.15s ease, transform 0.15s ease',
  },
  typingIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    padding: '8px 4px',
    minHeight: '28px',
  },
  typingDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: '#D08A30',
  },
  inputArea: {
    borderTop: '1px solid rgba(0, 0, 0, 0.07)',
    background: '#F5F4F0',
    padding: '0',
    maxWidth: '100%',
  },
  inputWrapper: {
    maxWidth: '768px',
    width: '100%',
    margin: '0 auto',
    padding: '12px 16px',
    boxSizing: 'border-box' as const,
  },
  inputWrapperMobile: {
    padding: '10px 12px',
    maxWidth: '100%',
    boxSizing: 'border-box' as const,
  },
  inputCard: {
    width: '100%',
    background: '#EDECE8',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '16px',
    padding: '4px 6px',
    boxShadow: 'none',
    boxSizing: 'border-box' as const,
  },
  inputFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 4px 0',
    maxWidth: '100%',
  },
  attachBtn: {
    width: '30px',
    height: '30px',
    borderRadius: '8px',
    border: 'none',
    background: 'transparent',
    color: '#9A9590',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
  },
  inputHint: {
    fontSize: '11px',
    color: '#9A9590',
    fontFamily: "'JetBrains Mono', 'SF Mono', 'Courier New', monospace",
  },
  inputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    width: '100%',
  },
  textarea: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    fontSize: '16px',
    fontFamily: 'inherit',
    resize: 'none' as const,
    outline: 'none',
    color: '#1A1918',
    padding: '8px 8px',
    maxHeight: '150px',
    minHeight: '36px',
    height: '36px',
    lineHeight: '20px',
    width: '100%',
    overflow: 'hidden' as const,
    verticalAlign: 'middle' as const,
  },
  sendBtn: {
    width: '36px',
    height: '36px',
    minWidth: '36px',
    minHeight: '36px',
    border: 'none',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #D08A30, #C05A30)',
    color: 'white',
    fontSize: '15px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'transform 0.15s ease, opacity 0.15s ease',
  },
  sendBtnDisabled: {
    opacity: 0.3,
    cursor: 'not-allowed',
    background: '#C4C0B8',
  },
  plusBtn: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    minHeight: '30px',
    border: 'none',
    borderRadius: '50%',
    background: 'transparent',
    color: '#9A9590',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'background 0.15s ease, color 0.15s ease',
  },
  plusMenu: {
    position: 'absolute' as const,
    bottom: '100%',
    left: 0,
    marginBottom: '8px',
    background: '#EDECE8',
    borderRadius: '12px',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)',
    padding: '8px 0',
    minWidth: '260px',
    zIndex: 1000,
  },
  plusMenuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    padding: '12px 16px',
    border: 'none',
    background: 'transparent',
    color: '#1A1918',
    fontSize: '14px',
    cursor: 'pointer',
    textAlign: 'left' as const,
    transition: 'background 0.15s ease',
    position: 'relative' as const,
  },
  plusMenuItemContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flex: 1,
  },
  upgradeBadge: {
    fontSize: '11px',
    fontWeight: 500,
    color: '#D08A30',
    background: 'rgba(208, 138, 48, 0.1)',
    padding: '3px 10px',
    borderRadius: '10px',
    marginLeft: 'auto',
  },
  modelSelect: {
    padding: '6px 0 0',
    textAlign: 'center' as const,
    fontSize: '11px',
    color: '#9A9590',
    maxWidth: '100%',
    overflow: 'hidden',
  },
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.4)',
    zIndex: 1100,
    backdropFilter: 'blur(4px)',
    WebkitBackdropFilter: 'blur(4px)',
  },
  modalContainer: {
    position: 'fixed' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 1101,
    maxWidth: '500px',
    width: '90%',
    maxHeight: '85vh',
    overflowY: 'auto' as const,
  },
  modalContent: {
    background: 'rgba(245, 244, 240, 0.95)',
    borderRadius: '20px',
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.1)',
    backdropFilter: 'blur(30px)',
    WebkitBackdropFilter: 'blur(30px)',
    border: '1px solid rgba(0, 0, 0, 0.07)',
  },
  modalHeader: {
    padding: '20px 24px 16px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.07)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: '17px',
    fontWeight: 600,
    color: '#1A1918',
    margin: 0,
  },
  modalCloseBtn: {
    background: 'rgba(0, 0, 0, 0.06)',
    border: 'none',
    borderRadius: '50%',
    width: '30px',
    height: '30px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#6B6660',
    transition: 'all 0.2s ease',
  },
  modalBody: {
    padding: '20px 28px 28px',
  },
  modalSection: {
    padding: '20px 24px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.07)',
  },
  modalSectionTitle: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
    color: '#9A9590',
    marginBottom: '14px',
  },
  modalSubsectionTitle: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
    color: '#9A9590',
    marginBottom: '14px',
    marginTop: '16px',
  },
  modalInfoRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
    fontSize: '13px',
  },
  modalLabel: {
    fontSize: '13px',
    color: '#6B6660',
  },
  modalValue: {
    fontSize: '13px',
    color: '#1A1918',
    fontWeight: 500,
  },
  planCurrentBadge: {
    padding: '16px 20px',
    background: '#f9f9f9',
    borderRadius: '12px',
    marginBottom: '16px',
  },
  planBadgeLarge: {
    display: 'inline-flex',
    padding: '4px 14px',
    borderRadius: '100px',
    fontWeight: 700,
    fontSize: '12px',
    background: 'linear-gradient(135deg, #D08A30, #C05A30)',
    color: '#fff',
  },
  planDescription: {
    color: '#9A9590',
    fontSize: '12px',
  },
  progressBarContainer: {
    width: '100%',
    height: '4px',
    background: '#e0e0e0',
    borderRadius: '4px',
    overflow: 'hidden',
    marginTop: '8px',
  },
  progressBar: {
    height: '100%',
    background: 'linear-gradient(90deg, #D08A30, #C05A30)',
    borderRadius: '4px',
    transition: 'width 0.5s ease',
  },
  plansGrid: {
    display: 'flex',
    gap: '10px',
    overflowX: 'auto' as const,
    paddingBottom: '8px',
  },
  planCard: {
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    background: '#F5F4F0',
    transition: 'all 0.2s',
    minWidth: '180px',
    flexShrink: 0,
  },
  planCardActive: {
    border: '2px solid #D08A30',
    background: 'rgba(208, 138, 48, 0.08)',
  },
  planCardTitle: {
    fontSize: '15px',
    fontWeight: 700,
    marginBottom: '6px',
    color: '#1A1918',
  },
  planPrice: {
    fontSize: '22px',
    fontWeight: 700,
    margin: '8px 0 12px',
    color: '#1A1918',
  },
  planPricePeriod: {
    fontSize: '13px',
    fontWeight: 400,
    color: '#6B6660',
  },
  planFeatures: {
    listStyle: 'none',
    marginBottom: '14px',
    padding: 0,
  },
  planFeature: {
    padding: '3px 0',
    fontSize: '11px',
    color: '#6B6660',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '4px',
  },
  checkMark: {
    color: '#D08A30',
    fontSize: '10px',
    fontWeight: 700,
    flexShrink: 0,
    marginRight: '2px',
  },
  planBtn: {
    width: '100%',
    marginTop: '12px',
    padding: '8px',
    borderRadius: '8px',
    border: '1px solid rgba(0, 0, 0, 0.13)',
    background: 'transparent',
    color: '#6B6660',
    fontFamily: 'Inter, sans-serif',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s',
    whiteSpace: 'nowrap' as const,
  },
  planBtnSpacer: {
    width: '100%',
    height: '36px',
  },
  logoutBtn: {
    width: '100%',
    padding: '13px 24px',
    background: 'rgba(232, 90, 90, 0.1)',
    color: '#E85A5A',
    border: '1px solid rgba(232, 90, 90, 0.3)',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  cancelSubscriptionBtn: {
    width: '100%',
    padding: '10px 16px',
    marginTop: '16px',
    background: 'transparent',
    color: '#9A9590',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  actionsModalContainer: {
    position: 'fixed' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 1101,
    width: '90%',
    maxWidth: '340px',
  },
  actionsModalContent: {
    background: 'rgba(245, 244, 240, 0.95)',
    borderRadius: '24px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.1)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    overflow: 'hidden',
  },
  actionsModalHeader: {
    padding: '20px 24px 16px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.07)',
  },
  actionsModalTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: '#1A1918',
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    textAlign: 'center' as const,
  },
  actionsModalBody: {
    padding: '16px 20px 20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
  },
  actionMenuItem: {
    width: '100%',
    padding: '13px 24px',
    background: '#EDECE8',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    textAlign: 'center' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s ease',
    color: '#1A1918',
  },
  actionMenuItemDanger: {
    background: 'rgba(232, 90, 90, 0.1)',
    border: '1px solid rgba(232, 90, 90, 0.3)',
    color: '#E85A5A',
  },
  actionMenuIcon: {
    fontSize: '16px',
  },
  deleteModalContainer: {
    position: 'fixed' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    zIndex: 1101,
    width: '90%',
    maxWidth: '400px',
  },
  deleteModalContent: {
    background: '#F5F4F0',
    borderRadius: '12px',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.15)',
  },
  deleteModalHeader: {
    padding: '20px 24px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.07)',
  },
  deleteModalTitle: {
    fontSize: '20px',
    fontWeight: 700,
    color: '#1A1918',
    margin: 0,
  },
  deleteModalBody: {
    padding: '20px 24px',
  },
  deleteModalText: {
    fontSize: '15px',
    color: '#6B6660',
    lineHeight: 1.5,
    margin: 0,
  },
  deleteModalFooter: {
    padding: '16px 24px',
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
  },
  deleteCancelBtn: {
    padding: '10px 20px',
    background: 'transparent',
    border: '1px solid rgba(0, 0, 0, 0.07)',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    color: '#1A1918',
  },
  deleteConfirmBtn: {
    padding: '10px 20px',
    background: '#E85A5A',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    color: 'white',
  },
};

// Dark Mode Styles (PRIMARY theme)
export const darkStyles: { [key: string]: React.CSSProperties } = {
  ...lightStyles,
  loadingContainer: {
    ...lightStyles.loadingContainer,
    background: 'linear-gradient(135deg, #0C0C0E 0%, #141416 100%)',
  },
  loadingLogo: {
    ...lightStyles.loadingLogo,
  },
  loadingLogoImg: {
    ...lightStyles.loadingLogoImg,
  },
  loadingBrand: {
    ...lightStyles.loadingBrand,
    color: '#E8E6E1',
  },
  loadingDot: {
    ...lightStyles.loadingDot,
    background: '#E8A04C',
  },
  limitWarning: {
    ...lightStyles.limitWarning,
    background: 'rgba(232, 160, 76, 0.1)',
    border: '1px solid rgba(232, 160, 76, 0.3)',
    color: '#E8A04C',
  },
  upgradeLink: {
    ...lightStyles.upgradeLink,
    color: '#E8A04C',
  },
  messageLimitInfo: {
    ...lightStyles.messageLimitInfo,
    color: '#6B6660',
  },
  remainingMessages: {
    ...lightStyles.remainingMessages,
    color: '#6B6660',
  },
  authContainer: {
    ...lightStyles.authContainer,
    background: '#0C0C0E',
  },
  authThemeToggle: {
    ...lightStyles.authThemeToggle,
    background: '#1E1E20',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#E8E6E1',
  },
  authCard: {
    ...lightStyles.authCard,
    background: 'rgba(20, 20, 22, 0.9)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.5)',
  },
  authTitle: {
    ...lightStyles.authTitle,
    color: '#E8E6E1',
  },
  authSubtitle: {
    ...lightStyles.authSubtitle,
    color: '#6B6660',
  },
  logoIconImg: {
    ...lightStyles.logoIconImg,
  },
  authError: {
    ...lightStyles.authError,
    background: 'rgba(232, 90, 90, 0.1)',
    borderLeft: '4px solid #E85A5A',
    color: '#E85A5A',
  },
  authSuccess: {
    ...lightStyles.authSuccess,
    background: 'rgba(16, 185, 129, 0.15)',
  },
  tabContainer: {
    ...lightStyles.tabContainer,
    background: 'rgba(255, 255, 255, 0.04)',
  },
  tab: {
    ...lightStyles.tab,
    color: '#6B6660',
  },
  tabActive: {
    ...lightStyles.tabActive,
    background: 'rgba(232, 160, 76, 0.1)',
    color: '#E8A04C',
    boxShadow: 'none',
  },
  labelRow: {
    ...lightStyles.labelRow,
  },
  label: {
    ...lightStyles.label,
    color: '#E8E6E1',
  },
  forgotLink: {
    ...lightStyles.forgotLink,
    color: '#6B6660',
  },
  input: {
    ...lightStyles.input,
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#E8E6E1',
  },
  authBtn: {
    ...lightStyles.authBtn,
    background: 'linear-gradient(135deg, #E8A04C, #E8624C)',
    color: '#fff',
    border: 'none',
  },
  divider: {
    ...lightStyles.divider,
    color: '#6B6660',
  },
  dividerLine: {
    ...lightStyles.dividerLine,
    background: 'rgba(255, 255, 255, 0.06)',
  },
  dividerText: {
    ...lightStyles.dividerText,
    color: '#6B6660',
  },
  socialButtons: {
    ...lightStyles.socialButtons,
  },
  authSwitch: {
    ...lightStyles.authSwitch,
    color: '#6B6660',
  },
  authLink: {
    ...lightStyles.authLink,
    color: '#E8A04C',
  },
  emailIcon: {
    ...lightStyles.emailIcon,
    background: 'rgba(232, 160, 76, 0.1)',
    border: '2px solid rgba(232, 160, 76, 0.3)',
    color: '#E8A04C',
  },
  emailIconRing: {
    ...lightStyles.emailIconRing,
    border: '2px solid rgba(232, 160, 76, 0.15)',
  },
  checkEmailTitle: {
    ...lightStyles.checkEmailTitle,
    color: '#E8E6E1',
  },
  checkEmailText: {
    ...lightStyles.checkEmailText,
    color: '#6B6660',
  },
  checkEmailAddress: {
    ...lightStyles.checkEmailAddress,
    color: '#E8A04C',
  },
  checkEmailSubtext: {
    ...lightStyles.checkEmailSubtext,
    color: '#6B6660',
  },
  mobileOverlay: {
    ...lightStyles.mobileOverlay,
    background: 'rgba(0, 0, 0, 0.6)',
  },
  mobileMenuBtn: {
    ...lightStyles.mobileMenuBtn,
    color: '#E8E6E1',
  },
  mobileMenuDots: {
    ...lightStyles.mobileMenuDots,
    color: '#6B6660',
  },
  sidebar: {
    ...lightStyles.sidebar,
    background: '#141416',
    borderRight: '1px solid rgba(255, 255, 255, 0.06)',
  },
  sidebarCollapsed: {
    ...lightStyles.sidebarCollapsed,
  },
  expandBtn: {
    ...lightStyles.expandBtn,
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#8A8690',
  },
  sidebarHeader: {
    ...lightStyles.sidebarHeader,
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  sidebarToggle: {
    ...lightStyles.sidebarToggle,
    color: '#E8E6E1',
  },
  brand: {
    ...lightStyles.brand,
    color: '#E8E6E1',
  },
  brandLogo: {
    ...lightStyles.brandLogo,
  },
  section: {
    ...lightStyles.section,
    borderBottom: 'none',
  },
  newChatBtn: {
    ...lightStyles.newChatBtn,
    border: '1px dashed rgba(255, 255, 255, 0.12)',
    color: '#8A8690',
  },
  newChatBtnHover: {
    ...lightStyles.newChatBtnHover,
    border: '1px dashed #E8A04C',
    background: 'rgba(232, 160, 76, 0.12)',
    color: '#E8A04C',
  },
  collapseBtn: {
    ...lightStyles.collapseBtn,
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#7A7680',
  },
  navText: {
    ...lightStyles.navText,
    color: '#E8E6E1',
  },
  sectionLabel: {
    ...lightStyles.sectionLabel,
    color: '#6B6660',
  },
  greetingLogoImg: {
    ...lightStyles.greetingLogoImg,
  },
  greetingText: {
    ...lightStyles.greetingText,
    color: '#F0EDE8',
  },
  promptChip: {
    ...lightStyles.promptChip,
    background: '#1E1E20',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#9A9590',
  },
  promptChipHover: {
    ...lightStyles.promptChipHover,
    background: 'rgba(232, 160, 76, 0.1)',
    border: '1px solid #E8A04C',
    color: '#E8A04C',
  },
  quickChip: {
    ...lightStyles.quickChip,
    border: '1px solid rgba(255, 255, 255, 0.06)',
    background: '#141416',
    color: '#8A8690',
  },
  quickChipHover: {
    ...lightStyles.quickChipHover,
    border: '1px solid #E8A04C',
    background: 'rgba(232, 160, 76, 0.12)',
    color: '#E8A04C',
    boxShadow: '0 4px 16px rgba(232, 160, 76, 0.1)',
  },
  chipIcon: {
    ...lightStyles.chipIcon,
    background: '#1A1A1E',
  },
  recentItem: {
    ...lightStyles.recentItem,
    color: '#E8E6E1',
  },
  recentItemActive: {
    ...lightStyles.recentItemActive,
    background: 'rgba(232, 160, 76, 0.08)',
    boxShadow: 'inset 3px 0 0 #E8A04C',
    color: '#F0EDE8',
  },
  renameInput: {
    ...lightStyles.renameInput,
    background: '#1E1E20',
    color: '#E8E6E1',
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  sidebarFooter: {
    ...lightStyles.sidebarFooter,
    borderTop: '1px solid rgba(255, 255, 255, 0.06)',
  },
  avatar: {
    ...lightStyles.avatar,
    background: 'linear-gradient(135deg, #E8A04C, #E8624C)',
  },
  main: {
    ...lightStyles.main,
    background: '#0C0C0E',
    backgroundImage: 'radial-gradient(ellipse 80% 50% at 50% 0%, rgba(232, 160, 76, 0.06), transparent), radial-gradient(circle at 80% 90%, rgba(232, 98, 76, 0.03), transparent)',
  },
  topBar: {
    ...lightStyles.topBar,
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  modelBadge: {
    ...lightStyles.modelBadge,
    color: '#8A8690',
  },
  scrollToBottomBtn: {
    ...lightStyles.scrollToBottomBtn,
    background: 'rgba(30, 30, 32, 0.95)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#E8E6E1',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
  },
  messageBubbleUser: {
    ...lightStyles.messageBubbleUser,
    background: 'rgba(232, 160, 76, 0.15)',
    color: '#E8E6E1',
  },
  messageBubbleAssistant: {
    ...lightStyles.messageBubbleAssistant,
    background: '#141416',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#E8E6E1',
  },
  messageTimestamp: {
    ...lightStyles.messageTimestamp,
    color: '#6B6660',
  },
  actionButton: {
    ...lightStyles.actionButton,
    color: '#6B6660',
  },
  typingDot: {
    ...lightStyles.typingDot,
    background: '#E8A04C',
  },
  editTextarea: {
    ...lightStyles.editTextarea,
    background: '#1E1E20',
    color: '#E8E6E1',
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  editWarning: {
    ...lightStyles.editWarning,
    color: '#6B6660',
  },
  editCancelBtn: {
    ...lightStyles.editCancelBtn,
    background: '#1E1E20',
    border: 'none',
    color: '#E8E6E1',
  },
  editSaveBtn: {
    ...lightStyles.editSaveBtn,
    background: 'linear-gradient(135deg, #E8A04C, #E8624C)',
    color: '#fff',
  },
  inputArea: {
    ...lightStyles.inputArea,
    borderTop: '1px solid rgba(255, 255, 255, 0.06)',
    background: '#0C0C0E',
  },
  inputCard: {
    ...lightStyles.inputCard,
    background: '#141416',
    border: '1px solid rgba(255, 255, 255, 0.12)',
    boxShadow: 'none',
  },
  inputFooter: {
    ...lightStyles.inputFooter,
  },
  attachBtn: {
    ...lightStyles.attachBtn,
    color: '#7A7680',
  },
  inputHint: {
    ...lightStyles.inputHint,
    color: '#7A7680',
  },
  textarea: {
    ...lightStyles.textarea,
    color: '#E8E6E1',
  },
  sendBtn: {
    ...lightStyles.sendBtn,
    background: 'linear-gradient(135deg, #E8A04C, #E8624C)',
  },
  sendBtnDisabled: {
    ...lightStyles.sendBtnDisabled,
    opacity: 0.3,
    background: '#2A2A2C',
  },
  plusBtn: {
    ...lightStyles.plusBtn,
    color: '#6B6660',
  },
  plusMenu: {
    ...lightStyles.plusMenu,
    background: '#141416',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.4)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  plusMenuItem: {
    ...lightStyles.plusMenuItem,
    color: '#E8E6E1',
  },
  plusMenuItemContent: {
    ...lightStyles.plusMenuItemContent,
  },
  upgradeBadge: {
    ...lightStyles.upgradeBadge,
    color: '#E8A04C',
    background: 'rgba(232, 160, 76, 0.1)',
  },
  modelSelect: {
    ...lightStyles.modelSelect,
    color: '#6B6660',
  },
  modalOverlay: {
    ...lightStyles.modalOverlay,
    background: 'rgba(0, 0, 0, 0.6)',
  },
  modalContent: {
    ...lightStyles.modalContent,
    background: 'rgba(20, 20, 22, 0.95)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    boxShadow: '0 12px 40px rgba(0, 0, 0, 0.5)',
  },
  modalHeader: {
    ...lightStyles.modalHeader,
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  modalTitle: {
    ...lightStyles.modalTitle,
    color: '#E8E6E1',
  },
  modalCloseBtn: {
    ...lightStyles.modalCloseBtn,
    background: 'rgba(255, 255, 255, 0.06)',
    color: '#6B6660',
  },
  modalSection: {
    ...lightStyles.modalSection,
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  modalSectionTitle: {
    ...lightStyles.modalSectionTitle,
    color: '#7A7680',
  },
  modalSubsectionTitle: {
    ...lightStyles.modalSubsectionTitle,
    color: '#7A7680',
  },
  modalInfoRow: {
    ...lightStyles.modalInfoRow,
  },
  modalLabel: {
    ...lightStyles.modalLabel,
    color: '#8A8690',
  },
  modalValue: {
    ...lightStyles.modalValue,
    color: '#F0EDE8',
  },
  planCurrentBadge: {
    ...lightStyles.planCurrentBadge,
    background: '#1A1A1E',
  },
  planBadgeLarge: {
    ...lightStyles.planBadgeLarge,
    background: 'linear-gradient(135deg, #E8A04C, #E8624C)',
    color: '#0C0C0E',
  },
  planDescription: {
    ...lightStyles.planDescription,
    color: '#7A7680',
  },
  progressBarContainer: {
    ...lightStyles.progressBarContainer,
    background: '#1A1A1E',
  },
  progressBar: {
    ...lightStyles.progressBar,
    background: 'linear-gradient(90deg, #E8A04C, #E8624C)',
  },
  planCard: {
    ...lightStyles.planCard,
    border: '1px solid rgba(255, 255, 255, 0.06)',
    background: '#0C0C0E',
  },
  planCardActive: {
    ...lightStyles.planCardActive,
    border: '2px solid #E8A04C',
    background: 'rgba(232, 160, 76, 0.08)',
  },
  planCardTitle: {
    ...lightStyles.planCardTitle,
    color: '#E8E6E1',
  },
  planPrice: {
    ...lightStyles.planPrice,
    color: '#E8E6E1',
  },
  planPricePeriod: {
    ...lightStyles.planPricePeriod,
    color: '#6B6660',
  },
  planFeature: {
    ...lightStyles.planFeature,
    color: '#8A8690',
  },
  checkMark: {
    ...lightStyles.checkMark,
    color: '#E8A04C',
  },
  planBtn: {
    ...lightStyles.planBtn,
    border: '1px solid rgba(255, 255, 255, 0.12)',
    background: 'transparent',
    color: '#8A8690',
  },
  logoutBtn: {
    ...lightStyles.logoutBtn,
    background: 'rgba(232, 90, 90, 0.1)',
    border: '1px solid rgba(232, 90, 90, 0.3)',
    color: '#E85A5A',
  },
  cancelSubscriptionBtn: {
    ...lightStyles.cancelSubscriptionBtn,
    color: '#6B6660',
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  actionsModalContent: {
    ...lightStyles.actionsModalContent,
    background: 'rgba(20, 20, 22, 0.95)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
  actionsModalHeader: {
    ...lightStyles.actionsModalHeader,
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  actionsModalTitle: {
    ...lightStyles.actionsModalTitle,
    color: '#E8E6E1',
  },
  actionMenuItem: {
    ...lightStyles.actionMenuItem,
    background: '#1E1E20',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#E8E6E1',
  },
  actionMenuItemDanger: {
    ...lightStyles.actionMenuItemDanger,
    background: 'rgba(232, 90, 90, 0.1)',
    border: '1px solid rgba(232, 90, 90, 0.3)',
    color: '#E85A5A',
  },
  deleteModalContent: {
    ...lightStyles.deleteModalContent,
    background: '#141416',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.5)',
  },
  deleteModalHeader: {
    ...lightStyles.deleteModalHeader,
    borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
  },
  deleteModalTitle: {
    ...lightStyles.deleteModalTitle,
    color: '#E8E6E1',
  },
  deleteModalText: {
    ...lightStyles.deleteModalText,
    color: '#6B6660',
  },
  deleteCancelBtn: {
    ...lightStyles.deleteCancelBtn,
    border: '1px solid rgba(255, 255, 255, 0.06)',
    color: '#E8E6E1',
  },
  deleteConfirmBtn: {
    ...lightStyles.deleteConfirmBtn,
    background: '#E85A5A',
  },
};
